// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: sport.proto

package sportgrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Button int32

const (
	Button_BUTTON_RESET Button = 0 // protolint:disable:this ENUM_FIELD_NAMES_PREFIX
	Button_BUTTON_F1    Button = 1
	Button_BUTTON_F2    Button = 2
	Button_BUTTON_F3    Button = 3
	Button_BUTTON_PLUS  Button = 4
	Button_BUTTON_MINUS Button = 5
)

// Enum value maps for Button.
var (
	Button_name = map[int32]string{
		0: "BUTTON_RESET",
		1: "BUTTON_F1",
		2: "BUTTON_F2",
		3: "BUTTON_F3",
		4: "BUTTON_PLUS",
		5: "BUTTON_MINUS",
	}
	Button_value = map[string]int32{
		"BUTTON_RESET": 0,
		"BUTTON_F1":    1,
		"BUTTON_F2":    2,
		"BUTTON_F3":    3,
		"BUTTON_PLUS":  4,
		"BUTTON_MINUS": 5,
	}
)

func (x Button) Enum() *Button {
	p := new(Button)
	*p = x
	return p
}

func (x Button) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Button) Descriptor() protoreflect.EnumDescriptor {
	return file_sport_proto_enumTypes[0].Descriptor()
}

func (Button) Type() protoreflect.EnumType {
	return &file_sport_proto_enumTypes[0]
}

func (x Button) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Button.Descriptor instead.
func (Button) EnumDescriptor() ([]byte, []int) {
	return file_sport_proto_rawDescGZIP(), []int{0}
}

type PerformanceType int32

const (
	PerformanceType_PERFORMANCE_TYPE_SPEED       PerformanceType = 0 // protolint:disable:this ENUM_FIELD_NAMES_PREFIX
	PerformanceType_PERFORMANCE_TYPE_POWER       PerformanceType = 1
	PerformanceType_PERFORMANCE_TYPE_CADENCE     PerformanceType = 2
	PerformanceType_PERFORMANCE_TYPE_HEART_RATE  PerformanceType = 3
	PerformanceType_PERFORMANCE_TYPE_CALIBRATION PerformanceType = 4
)

// Enum value maps for PerformanceType.
var (
	PerformanceType_name = map[int32]string{
		0: "PERFORMANCE_TYPE_SPEED",
		1: "PERFORMANCE_TYPE_POWER",
		2: "PERFORMANCE_TYPE_CADENCE",
		3: "PERFORMANCE_TYPE_HEART_RATE",
		4: "PERFORMANCE_TYPE_CALIBRATION",
	}
	PerformanceType_value = map[string]int32{
		"PERFORMANCE_TYPE_SPEED":       0,
		"PERFORMANCE_TYPE_POWER":       1,
		"PERFORMANCE_TYPE_CADENCE":     2,
		"PERFORMANCE_TYPE_HEART_RATE":  3,
		"PERFORMANCE_TYPE_CALIBRATION": 4,
	}
)

func (x PerformanceType) Enum() *PerformanceType {
	p := new(PerformanceType)
	*p = x
	return p
}

func (x PerformanceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PerformanceType) Descriptor() protoreflect.EnumDescriptor {
	return file_sport_proto_enumTypes[1].Descriptor()
}

func (PerformanceType) Type() protoreflect.EnumType {
	return &file_sport_proto_enumTypes[1]
}

func (x PerformanceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PerformanceType.Descriptor instead.
func (PerformanceType) EnumDescriptor() ([]byte, []int) {
	return file_sport_proto_rawDescGZIP(), []int{1}
}

type DataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataRequest) Reset() {
	*x = DataRequest{}
	mi := &file_sport_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataRequest) ProtoMessage() {}

func (x *DataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sport_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataRequest.ProtoReflect.Descriptor instead.
func (*DataRequest) Descriptor() ([]byte, []int) {
	return file_sport_proto_rawDescGZIP(), []int{0}
}

type LoadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	TargetLoad    int32                  `protobuf:"varint,2,opt,name=target_load,json=targetLoad,proto3" json:"target_load,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadRequest) Reset() {
	*x = LoadRequest{}
	mi := &file_sport_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadRequest) ProtoMessage() {}

func (x *LoadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sport_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadRequest.ProtoReflect.Descriptor instead.
func (*LoadRequest) Descriptor() ([]byte, []int) {
	return file_sport_proto_rawDescGZIP(), []int{1}
}

func (x *LoadRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *LoadRequest) GetTargetLoad() int32 {
	if x != nil {
		return x.TargetLoad
	}
	return 0
}

type LoadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadResponse) Reset() {
	*x = LoadResponse{}
	mi := &file_sport_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadResponse) ProtoMessage() {}

func (x *LoadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sport_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadResponse.ProtoReflect.Descriptor instead.
func (*LoadResponse) Descriptor() ([]byte, []int) {
	return file_sport_proto_rawDescGZIP(), []int{2}
}

type RecalibrateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecalibrateRequest) Reset() {
	*x = RecalibrateRequest{}
	mi := &file_sport_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecalibrateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecalibrateRequest) ProtoMessage() {}

func (x *RecalibrateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sport_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecalibrateRequest.ProtoReflect.Descriptor instead.
func (*RecalibrateRequest) Descriptor() ([]byte, []int) {
	return file_sport_proto_rawDescGZIP(), []int{3}
}

func (x *RecalibrateRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

type RecalibrateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecalibrateResponse) Reset() {
	*x = RecalibrateResponse{}
	mi := &file_sport_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecalibrateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecalibrateResponse) ProtoMessage() {}

func (x *RecalibrateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sport_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecalibrateResponse.ProtoReflect.Descriptor instead.
func (*RecalibrateResponse) Descriptor() ([]byte, []int) {
	return file_sport_proto_rawDescGZIP(), []int{4}
}

type SportData struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DeviceId        string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	ControlData     *ControlData           `protobuf:"bytes,2,opt,name=control_data,json=controlData,proto3" json:"control_data,omitempty"`
	PerformanceData *PerformanceData       `protobuf:"bytes,3,opt,name=performance_data,json=performanceData,proto3" json:"performance_data,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SportData) Reset() {
	*x = SportData{}
	mi := &file_sport_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SportData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SportData) ProtoMessage() {}

func (x *SportData) ProtoReflect() protoreflect.Message {
	mi := &file_sport_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SportData.ProtoReflect.Descriptor instead.
func (*SportData) Descriptor() ([]byte, []int) {
	return file_sport_proto_rawDescGZIP(), []int{5}
}

func (x *SportData) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *SportData) GetControlData() *ControlData {
	if x != nil {
		return x.ControlData
	}
	return nil
}

func (x *SportData) GetPerformanceData() *PerformanceData {
	if x != nil {
		return x.PerformanceData
	}
	return nil
}

type ControlData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pressed       []Button               `protobuf:"varint,1,rep,packed,name=pressed,proto3,enum=sportgrpc.Button" json:"pressed,omitempty"` // protolint:disable:this REPEATED_FIELD_NAMES_PLURALIZED
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlData) Reset() {
	*x = ControlData{}
	mi := &file_sport_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlData) ProtoMessage() {}

func (x *ControlData) ProtoReflect() protoreflect.Message {
	mi := &file_sport_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlData.ProtoReflect.Descriptor instead.
func (*ControlData) Descriptor() ([]byte, []int) {
	return file_sport_proto_rawDescGZIP(), []int{6}
}

func (x *ControlData) GetPressed() []Button {
	if x != nil {
		return x.Pressed
	}
	return nil
}

type PerformanceData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          PerformanceType        `protobuf:"varint,1,opt,name=type,proto3,enum=sportgrpc.PerformanceType" json:"type,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PerformanceData) Reset() {
	*x = PerformanceData{}
	mi := &file_sport_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PerformanceData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PerformanceData) ProtoMessage() {}

func (x *PerformanceData) ProtoReflect() protoreflect.Message {
	mi := &file_sport_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PerformanceData.ProtoReflect.Descriptor instead.
func (*PerformanceData) Descriptor() ([]byte, []int) {
	return file_sport_proto_rawDescGZIP(), []int{7}
}

func (x *PerformanceData) GetType() PerformanceType {
	if x != nil {
		return x.Type
	}
	return PerformanceType_PERFORMANCE_TYPE_SPEED
}

func (x *PerformanceData) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_sport_proto protoreflect.FileDescriptor

const file_sport_proto_rawDesc = "" +
	"\n" +
	"\vsport.proto\x12\tsportgrpc\"\r\n" +
	"\vDataRequest\"K\n" +
	"\vLoadRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1f\n" +
	"\vtarget_load\x18\x02 \x01(\x05R\n" +
	"targetLoad\"\x0e\n" +
	"\fLoadResponse\"1\n" +
	"\x12RecalibrateRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\"\x15\n" +
	"\x13RecalibrateResponse\"\xaa\x01\n" +
	"\tSportData\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x129\n" +
	"\fcontrol_data\x18\x02 \x01(\v2\x16.sportgrpc.ControlDataR\vcontrolData\x12E\n" +
	"\x10performance_data\x18\x03 \x01(\v2\x1a.sportgrpc.PerformanceDataR\x0fperformanceData\":\n" +
	"\vControlData\x12+\n" +
	"\apressed\x18\x01 \x03(\x0e2\x11.sportgrpc.ButtonR\apressed\"W\n" +
	"\x0fPerformanceData\x12.\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1a.sportgrpc.PerformanceTypeR\x04type\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value*j\n" +
	"\x06Button\x12\x10\n" +
	"\fBUTTON_RESET\x10\x00\x12\r\n" +
	"\tBUTTON_F1\x10\x01\x12\r\n" +
	"\tBUTTON_F2\x10\x02\x12\r\n" +
	"\tBUTTON_F3\x10\x03\x12\x0f\n" +
	"\vBUTTON_PLUS\x10\x04\x12\x10\n" +
	"\fBUTTON_MINUS\x10\x05*\xaa\x01\n" +
	"\x0fPerformanceType\x12\x1a\n" +
	"\x16PERFORMANCE_TYPE_SPEED\x10\x00\x12\x1a\n" +
	"\x16PERFORMANCE_TYPE_POWER\x10\x01\x12\x1c\n" +
	"\x18PERFORMANCE_TYPE_CADENCE\x10\x02\x12\x1f\n" +
	"\x1bPERFORMANCE_TYPE_HEART_RATE\x10\x03\x12 \n" +
	"\x1cPERFORMANCE_TYPE_CALIBRATION\x10\x042\xd8\x01\n" +
	"\n" +
	"Controller\x12<\n" +
	"\bReadData\x12\x16.sportgrpc.DataRequest\x1a\x14.sportgrpc.SportData\"\x000\x01\x12<\n" +
	"\aSetLoad\x12\x16.sportgrpc.LoadRequest\x1a\x17.sportgrpc.LoadResponse\"\x00\x12N\n" +
	"\vRecalibrate\x12\x1d.sportgrpc.RecalibrateRequest\x1a\x1e.sportgrpc.RecalibrateResponse\"\x00B\rZ\v./sportgrpcb\x06proto3"

var (
	file_sport_proto_rawDescOnce sync.Once
	file_sport_proto_rawDescData []byte
)

func file_sport_proto_rawDescGZIP() []byte {
	file_sport_proto_rawDescOnce.Do(func() {
		file_sport_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sport_proto_rawDesc), len(file_sport_proto_rawDesc)))
	})
	return file_sport_proto_rawDescData
}

var file_sport_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_sport_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_sport_proto_goTypes = []any{
	(Button)(0),                 // 0: sportgrpc.Button
	(PerformanceType)(0),        // 1: sportgrpc.PerformanceType
	(*DataRequest)(nil),         // 2: sportgrpc.DataRequest
	(*LoadRequest)(nil),         // 3: sportgrpc.LoadRequest
	(*LoadResponse)(nil),        // 4: sportgrpc.LoadResponse
	(*RecalibrateRequest)(nil),  // 5: sportgrpc.RecalibrateRequest
	(*RecalibrateResponse)(nil), // 6: sportgrpc.RecalibrateResponse
	(*SportData)(nil),           // 7: sportgrpc.SportData
	(*ControlData)(nil),         // 8: sportgrpc.ControlData
	(*PerformanceData)(nil),     // 9: sportgrpc.PerformanceData
}
var file_sport_proto_depIdxs = []int32{
	8, // 0: sportgrpc.SportData.control_data:type_name -> sportgrpc.ControlData
	9, // 1: sportgrpc.SportData.performance_data:type_name -> sportgrpc.PerformanceData
	0, // 2: sportgrpc.ControlData.pressed:type_name -> sportgrpc.Button
	1, // 3: sportgrpc.PerformanceData.type:type_name -> sportgrpc.PerformanceType
	2, // 4: sportgrpc.Controller.ReadData:input_type -> sportgrpc.DataRequest
	3, // 5: sportgrpc.Controller.SetLoad:input_type -> sportgrpc.LoadRequest
	5, // 6: sportgrpc.Controller.Recalibrate:input_type -> sportgrpc.RecalibrateRequest
	7, // 7: sportgrpc.Controller.ReadData:output_type -> sportgrpc.SportData
	4, // 8: sportgrpc.Controller.SetLoad:output_type -> sportgrpc.LoadResponse
	6, // 9: sportgrpc.Controller.Recalibrate:output_type -> sportgrpc.RecalibrateResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_sport_proto_init() }
func file_sport_proto_init() {
	if File_sport_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sport_proto_rawDesc), len(file_sport_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sport_proto_goTypes,
		DependencyIndexes: file_sport_proto_depIdxs,
		EnumInfos:         file_sport_proto_enumTypes,
		MessageInfos:      file_sport_proto_msgTypes,
	}.Build()
	File_sport_proto = out.File
	file_sport_proto_goTypes = nil
	file_sport_proto_depIdxs = nil
}
